version: '3.9'

services:
  db:
    image: mysql:8.0.32
    # container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gyoza
      MYSQL_USER: gyoza
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

